version: '3'

services:
  # Serviço para o seu aplicativo
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["php", "./app/Core.php"]
    stdin_open: true  
    tty: true 
    ports:
      - "8080:80"  

  # Serviço para os testes
  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["php", "./vendor/bin/phpunit", "--bootstrap", "vendor/autoload.php", "tests"]